cargo-features = ["profile-rustflags"]

[workspace]
resolver = "3"
members = [
    "sada-byondapi",
    "sada-client",
    "sada-client-async",
    "sada-common",
    "sada-ipc",
    "sada-server",
    "sada-utils",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
axum = { version = "0.8", features = ["ws"] }
bindgen = "0.73.2"
doxygen-rs = "0.4.2"
flume = "0.12.0"
futures-util = "0.3"
hound = "3.5"
libloading = "0.9.0"
opus = "0.3"
paste = "1.0.15"
postcard = { version = "1", features = ["use-std"] }
rustc-hash = "2.1"
sada-common = { path = "sada-common" }
sada-byondapi = { path = "sada-byondapi" }
sada-ipc = { path = "sada-ipc" }
sada-utils = { path = "sada-utils" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
str0m = "0.23.1"
systemstat = "0.2.2"
thiserror = "2"
tokio = "1"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
missing_docs_in_private_items = "warn"

[profile.release]
rustflags = ["-C", "target-cpu=native"]
opt-level = 3
lto = true
codegen-units = 1
debug = true
strip = "debuginfo"
split-debuginfo = "off"

[profile.dist]
inherits = "release"
rustflags = []
