[package]
name = "sada-client"
version.workspace = true
edition.workspace = true

[lib]
name = "sada"
crate-type = ["cdylib"]

[dependencies]
flume.workspace = true
sada-byondapi = { workspace = true, features = ["byond-await"] }
sada-common = { workspace = true, features = ["byondapi"] }
sada-ipc.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
