[package]
name = "sada-client"
version.workspace = true
edition.workspace = true

[lib]
name = "sada"
crate-type = ["cdylib"]

[dependencies]
flume.workspace = true
sada-byondapi = { workspace = true, features = ["sada"] }
sada-common = { workspace = true, features = ["byondapi"] }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"], optional = true }

[features]
default = []
async = ["sada-byondapi/async", "dep:tokio"]

[lints]
workspace = true
