[alias]
build-client = "build -p sada-client --target i686-unknown-linux-gnu"
build-server = "build -p sada-server"

[build]
rustdocflags = ["--document-private-items"]

[env]
AWS_LC_SYS_PREBUILT_NASM = "1"
