#![allow(missing_docs)]

#[cfg(feature = "generate-bindings")]
const RULES: &str = r"#![allow(
    missing_docs,
    unused,
    unsafe_op_in_unsafe_fn,
    nonstandard_style,
    clippy::all,
    clippy::missing_docs_in_private_items
)]";

#[cfg(feature = "generate-bindings")]
fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=include/wrapper.hpp");
    println!("cargo:rerun-if-changed=include/byondapi.h");

    let bindings = bindgen::Builder::default()
        .header("include/wrapper.hpp")
        .dynamic_library_name("Byondapi")
        .dynamic_link_require_all(true)
        .override_abi(bindgen::Abi::CUnwind, "Byond.*")
        .allowlist_item("C?Byond.*")
        .generate_block(true)
        .layout_tests(false)
        .raw_line("//! Raw bindings generated by rust-bindgen.\n")
        .raw_line(RULES)
        .raw_line("#![rustfmt::skip]")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .parse_callbacks(Box::new(DoxygenCallbacks))
        .generate()?;

    bindings.write_to_file("src/bindings.rs")?;

    #[derive(Debug)]
    struct DoxygenCallbacks;

    impl bindgen::callbacks::ParseCallbacks for DoxygenCallbacks {
        fn process_comment(&self, comment: &str) -> Option<String> { Some(doxygen_rs::transform(comment)) }
    }

    Ok(())
}

#[cfg(not(feature = "generate-bindings"))]
fn main() {}
