[package]
name = "sada-byondapi"
version.workspace = true
edition.workspace = true

[dependencies]
libloading.workspace = true
paste.workspace = true
sada-utils = { workspace = true, features = ["shutdown"], optional = true }
tokio = { workspace = true, features = ["rt", "sync"], optional = true }

[build-dependencies]
bindgen = { workspace = true, optional = true }
doxygen-rs.workspace = true

[features]
default = []
async = ["dep:tokio", "dep:sada-utils"]
generate-bindings = ["dep:bindgen"]
sada = []

[lints]
workspace = true
