[package]
name = "sada-common"
version.workspace = true
edition.workspace = true

[dependencies]
sada-byondapi = { workspace = true, optional = true }
serde.workspace = true

[dev-dependencies]
postcard.workspace = true

[features]
default = []
byondapi = ["dep:sada-byondapi"]

[lints]
workspace = true
